service: helloWorld

provider:
  name: aws
  runtime: nodejs4.3

functions:
  helloWorld:
    handler: build/handler.helloWorld
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /
          method: POST

plugins:
  - serverless-offline
